### ISSUE TITLE
render.py is saving frames to the root (C:) and not the specified drive where the ....json and ...anim.blend were saved

### ISSUE THREAD

**Issue by john-aind** [connectome-neuprint/neuVid#125]
The first 8 steps in the "Code" section of this github page work perfectly, and I'm successfully able to run addAnimation.py and also view the iterations of the animation in a live, active/interactive blender session (not run in the background).
However, on step 9, the 241 frames are saved in the root drive (C:).
The assembleFrames.py script then fails, because the frames aren't where it expects.
If the frames are cut-and-paste to the correct folder, the script runs, but generates a video in the root drive (C:) with all black frames.
If the frames are copy-and-paste into the correct folder, the assembleFrames.py run and successfully generates a video in the root drive (C:), a successful work-around.

**Comment by hubbardp** [comment]
Thanks for reporting this issue.  It seems that Blender's behavior with Windows paths can be a bit unexpected.  I just checked in a fix, and neuVid version 1.16.1 should work better.  I will go ahead and close this issue, but feel free to create another one if you see any other problems.  Thanks again.
